"""Writes test/boost/BoostVectors.sol: a seed plus a deterministic 60-step path (rallies, a crash, keeper gaps of 3h, 10h
and 200h) replayed through the integer-exact reference. The Foundry tests must reproduce every value exactly."""
import json, os, random, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import boost_signal_ref as R
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
seed = json.load(open(os.path.join(ROOT, "deployments", "boost-eth-seed.json")))
ee = [int(x) for x in seed["ethEma"]]; be = [int(x) for x in seed["btcEma"]]
s = R.Signal(ee, be, seed["ethFlags"], seed["btcFlags"], int(seed["ethVar"]), int(seed["ethLast"]), seed["lastHour"])
rnd = random.Random(4663)
pe8 = int(seed["ethLast"]) // 10**10; pb8 = int(seed["btcLast"]) // 10**10
steps = []; off = 0
for k in range(60):
    gap = 3 if k == 10 else 10 if k == 25 else 200 if k == 40 else 1
    off += gap
    drift = -0.06 if 30 <= k < 36 else 0.02 if 45 <= k < 52 else 0.0     # a crash, then a rally
    pe8 = max(1, int(pe8 * (1 + drift + rnd.gauss(0, 0.01)))); pb8 = max(1, int(pb8 * (1 + drift * 0.7 + rnd.gauss(0, 0.008))))
    t = s.poke(seed["lastHour"] + off, pe8 * 10**10, pb8 * 10**10)
    steps.append((off, pe8, pb8, t, s.f["eth"], s.f["btc"], s.var, s.e["eth"][0], s.e["btc"][7], s.sigma()))
L = ["// SPDX-License-Identifier: MIT", "pragma solidity ^0.8.24;", "",
     "/// @dev GENERATED by research/boost/gen_vectors.py from deployments/boost-eth-seed.json. Do not edit by hand.",
     "library BoostVectors {",
     f"    uint256 internal constant SEED_HOUR = {seed['lastHour']};",
     f"    uint8 internal constant ETH_FLAGS = {seed['ethFlags']};", f"    uint8 internal constant BTC_FLAGS = {seed['btcFlags']};",
     f"    uint256 internal constant ETH_VAR = {seed['ethVar']};", f"    uint256 internal constant ETH_LAST = {seed['ethLast']};",
     f"    uint256 internal constant BTC_LAST = {seed['btcLast']};", f"    uint256 internal constant SEED_TARGET = {int(seed['target'] * 0) + R.Signal(ee, be, seed['ethFlags'], seed['btcFlags'], int(seed['ethVar']), int(seed['ethLast']), seed['lastHour']).target()};",
     "    function ethEma() internal pure returns (uint128[8] memory e) {"]
L += [f"        e[{i}] = {x};" for i, x in enumerate(ee)] + ["    }", "    function btcEma() internal pure returns (uint128[8] memory e) {"]
L += [f"        e[{i}] = {x};" for i, x in enumerate(be)] + ["    }",
      "    struct Step { uint256 hourOffset; int256 ethPrice8; int256 btcPrice8; uint256 target; uint8 ethFlags; uint8 btcFlags; uint256 ethVar; uint256 ethEma0; uint256 btcEma7; uint256 sigma; }",
      f"    function steps() internal pure returns (Step[] memory s) {{", f"        s = new Step[]({len(steps)});"]
L += [f"        s[{i}] = Step({a}, {b}, {c}, {d}, {e}, {f}, {g}, {h}, {j}, {m});" for i, (a, b, c, d, e, f, g, h, j, m) in enumerate(steps)]
L += ["    }", "}", ""]
open(os.path.join(ROOT, "test", "boost", "BoostVectors.sol"), "w").write("\n".join(L))
print("vectors:", len(steps), "| targets along the path:", " ".join(f"{x[3]/R.WAD:.2f}" for x in steps[::5]))
