[profile.default]
src = "contracts"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 1
via_ir = true
evm_version = "cancun"
bytecode_hash = "ipfs"

[profile.default.fuzz]
runs = 1024

[profile.default.invariant]
runs = 128
depth = 64
fail_on_revert = true
