// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {HoodxBoostSignalV1} from "../../contracts/boost/HoodxBoostSignalV1.sol";
import {BoostVectors} from "./BoostVectors.sol";

contract MockFeed {
    int256 public answer;
    uint256 public updatedAt;
    uint8 public decimals = 8;

    function set(int256 a, uint256 t) external {
        answer = a;
        updatedAt = t;
    }

    function setDecimals(uint8 d) external {
        decimals = d;
    }

    function latestRoundData() external view returns (uint80, int256, uint256, uint256, uint80) {
        return (1, answer, updatedAt, updatedAt, 1);
    }
}

/// @notice Unit tests for the on-chain signal. The vectors are generated by research/boost/gen_vectors.py from the
///         integer-exact Python port, which is itself checked against the 2016-2026 backtest (research/boost/equiv.py).
contract BoostSignalTest is Test {
    MockFeed eth;
    MockFeed btc;
    HoodxBoostSignalV1 sig;

    function setUp() public {
        vm.warp(BoostVectors.SEED_HOUR * 1 hours + 600);
        eth = new MockFeed();
        btc = new MockFeed();
        eth.set(int256(BoostVectors.ETH_LAST / 1e10), block.timestamp - 60);
        btc.set(int256(BoostVectors.BTC_LAST / 1e10), block.timestamp - 60);
        sig = _deploy();
    }

    function _deploy() internal returns (HoodxBoostSignalV1) {
        return new HoodxBoostSignalV1(
            address(eth), address(btc), 25 hours, 25 hours, BoostVectors.ethEma(), BoostVectors.btcEma(),
            BoostVectors.ETH_FLAGS, BoostVectors.BTC_FLAGS, BoostVectors.ETH_VAR, BoostVectors.ETH_LAST, BoostVectors.BTC_LAST
        );
    }

    function test_seedMatchesReference() public view {
        assertEq(sig.target(), BoostVectors.SEED_TARGET);
        assertEq(sig.lastHour(), BoostVectors.SEED_HOUR);
        assertEq(sig.ethVar(), BoostVectors.ETH_VAR);
        assertTrue(sig.isFresh());
    }

    /// The contract must reproduce the reference bit for bit over 60 pokes, including 3h, 10h and >168h keeper gaps.
    function test_replaysReferenceVectorsExactly() public {
        BoostVectors.Step[] memory s = BoostVectors.steps();
        for (uint256 i; i < s.length; ++i) {
            uint256 t = (BoostVectors.SEED_HOUR + s[i].hourOffset) * 1 hours + 120;
            vm.warp(t);
            eth.set(s[i].ethPrice8, t - 30);
            btc.set(s[i].btcPrice8, t - 30);
            uint256 got = sig.poke();
            (uint256 tg, uint256 sg, uint8 ef, uint8 bf, uint128[8] memory ee, uint128[8] memory be,,) = sig.snapshot();
            assertEq(got, s[i].target, "target");
            assertEq(tg, s[i].target, "snapshot target");
            assertEq(ef, s[i].ethFlags, "eth flags");
            assertEq(bf, s[i].btcFlags, "btc flags");
            assertEq(sig.ethVar(), s[i].ethVar, "variance");
            assertEq(ee[0], s[i].ethEma0, "eth ema20d");
            assertEq(be[7], s[i].btcEma7, "btc ema50d fast");
            assertEq(sg, s[i].sigma, "sigma");
        }
    }

    function test_pokeOncePerHour() public {
        vm.expectRevert(HoodxBoostSignalV1.TooSoon.selector);
        sig.poke();
        vm.warp((block.timestamp / 1 hours + 1) * 1 hours);
        eth.set(int256(BoostVectors.ETH_LAST / 1e10), block.timestamp);
        btc.set(int256(BoostVectors.BTC_LAST / 1e10), block.timestamp);
        sig.poke();
        vm.expectRevert(HoodxBoostSignalV1.TooSoon.selector);
        sig.poke();
    }

    function test_freshness() public {
        vm.warp((BoostVectors.SEED_HOUR + 2) * 1 hours + 3599);
        assertTrue(sig.isFresh());
        vm.warp((BoostVectors.SEED_HOUR + 3) * 1 hours);
        assertFalse(sig.isFresh());
    }

    function test_rejectsStaleFeeds() public {
        vm.warp(vm.getBlockTimestamp() + 2 hours);
        eth.set(int256(BoostVectors.ETH_LAST / 1e10), block.timestamp - 26 hours);
        btc.set(int256(BoostVectors.BTC_LAST / 1e10), block.timestamp);
        vm.expectRevert(HoodxBoostSignalV1.BadFeed.selector);
        sig.poke();
        eth.set(int256(BoostVectors.ETH_LAST / 1e10), block.timestamp);
        btc.set(int256(BoostVectors.BTC_LAST / 1e10), block.timestamp + 1); // from the future
        vm.expectRevert(HoodxBoostSignalV1.BadFeed.selector);
        sig.poke();
    }

    function test_rejectsNonPositiveAndAbsurdPrices() public {
        vm.warp(vm.getBlockTimestamp() + 2 hours);
        btc.set(int256(BoostVectors.BTC_LAST / 1e10), block.timestamp);
        eth.set(0, block.timestamp);
        vm.expectRevert(HoodxBoostSignalV1.BadFeed.selector);
        sig.poke();
        eth.set(-1, block.timestamp);
        vm.expectRevert(HoodxBoostSignalV1.BadFeed.selector);
        sig.poke();
        eth.set(int256(BoostVectors.ETH_LAST / 1e10) * 4, block.timestamp); // a 4x jump in one update is a broken feed
        vm.expectRevert(HoodxBoostSignalV1.BadFeed.selector);
        sig.poke();
        eth.set(int256(BoostVectors.ETH_LAST / 1e10) / 4, block.timestamp);
        vm.expectRevert(HoodxBoostSignalV1.BadFeed.selector);
        sig.poke();
    }

    function test_constructorChecksSeedAgainstLiveFeeds() public {
        eth.set(int256(BoostVectors.ETH_LAST / 1e10) * 104 / 100, block.timestamp); // seed 4% away from the feed
        vm.expectRevert(HoodxBoostSignalV1.Invalid.selector);
        _deploy();
        eth.set(int256(BoostVectors.ETH_LAST / 1e10), block.timestamp);
        btc.setDecimals(18);
        vm.expectRevert(HoodxBoostSignalV1.Invalid.selector);
        _deploy();
    }

    function test_constructorRejectsBadParams() public {
        uint128[8] memory z;
        vm.expectRevert(HoodxBoostSignalV1.Invalid.selector);
        new HoodxBoostSignalV1(address(eth), address(btc), 25 hours, 25 hours, z, BoostVectors.btcEma(), 0, 0, BoostVectors.ETH_VAR, BoostVectors.ETH_LAST, BoostVectors.BTC_LAST);
        vm.expectRevert(HoodxBoostSignalV1.Invalid.selector);
        new HoodxBoostSignalV1(address(eth), address(btc), 3 days, 25 hours, BoostVectors.ethEma(), BoostVectors.btcEma(), 0, 0, BoostVectors.ETH_VAR, BoostVectors.ETH_LAST, BoostVectors.BTC_LAST);
        vm.expectRevert(HoodxBoostSignalV1.Invalid.selector);
        new HoodxBoostSignalV1(address(eth), address(btc), 25 hours, 25 hours, BoostVectors.ethEma(), BoostVectors.btcEma(), 0, 0, 0, BoostVectors.ETH_LAST, BoostVectors.BTC_LAST);
        vm.expectRevert(HoodxBoostSignalV1.Invalid.selector);
        new HoodxBoostSignalV1(address(0xbeef), address(btc), 25 hours, 25 hours, BoostVectors.ethEma(), BoostVectors.btcEma(), 0, 0, BoostVectors.ETH_VAR, BoostVectors.ETH_LAST, BoostVectors.BTC_LAST);
    }

    /// Whatever the market does, the target stays within [0, CAP] and the state stays sane.
    function testFuzz_targetBounded(uint256 seed, uint8 n) public {
        n = uint8(bound(n, 1, 40));
        int256 pe = int256(BoostVectors.ETH_LAST / 1e10);
        int256 pb = int256(BoostVectors.BTC_LAST / 1e10);
        for (uint256 i; i < n; ++i) {
            seed = uint256(keccak256(abi.encode(seed, i)));
            uint256 gap = 1 + (seed % 7 == 0 ? seed % 300 : 0);
            vm.warp((vm.getBlockTimestamp() / 1 hours + gap) * 1 hours + 1);
            int256 me = int256(seed % 41) - 20; // -20% .. +20%
            int256 mb = int256((seed >> 8) % 41) - 20;
            pe = pe * (100 + me) / 100;
            pb = pb * (100 + mb) / 100;
            if (pe <= 0 || pb <= 0) return;
            eth.set(pe, block.timestamp);
            btc.set(pb, block.timestamp);
            uint256 t = sig.poke();
            assertLe(t, sig.CAP());
            assertLe(sig.sigma(), 50e18); // < 5,000% a year
        }
    }

    /// A long outage is applied as at most one week: the state converges toward the current price, never overshoots.
    function test_longGapConvergesWithoutOvershoot() public {
        uint256 p = BoostVectors.ETH_LAST * 6 / 10;
        vm.warp((BoostVectors.SEED_HOUR + 1000) * 1 hours + 1);
        eth.set(int256(p / 1e10), block.timestamp);
        btc.set(int256(BoostVectors.BTC_LAST / 1e10), block.timestamp);
        sig.poke();
        (,,,, uint128[8] memory ee,,,) = sig.snapshot();
        for (uint256 i; i < 8; ++i) {
            assertGe(ee[i], p - 1e10); // never below the new price
            assertLe(ee[i], BoostVectors.ethEma()[i]); // never above where it started
        }
        assertEq(sig.lastHour(), BoostVectors.SEED_HOUR + 1000);
    }
}
