export const vaultAbi = [
  {
    type: "function",
    name: "deposit",
    stateMutability: "payable",
    inputs: [{ type: "uint256", name: "minShares" }],
    outputs: [{ type: "uint256", name: "shares" }],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [
      { type: "uint256", name: "shares" },
      { type: "uint256", name: "minEthOut" },
    ],
    outputs: [{ type: "uint256", name: "net" }],
  },
  {
    type: "function",
    name: "previewDeposit",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "weiIn" }],
    outputs: [
      { type: "uint256", name: "shares" },
      { type: "uint256", name: "fee" },
    ],
  },
  {
    type: "function",
    name: "previewBuy",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "weiIn" }],
    outputs: [
      { type: "uint256", name: "spent" },
      { type: "uint256", name: "wethKept" },
      { type: "uint256", name: "names" },
    ],
  },
  {
    type: "function",
    name: "previewSell",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "shares" }],
    outputs: [
      { type: "uint256", name: "minEthOut" },
      { type: "uint256", name: "names" },
    ],
  },
  {
    type: "function",
    name: "previewWithdraw",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "shares" }],
    outputs: [
      { type: "uint256", name: "net" },
      { type: "uint256", name: "fee" },
    ],
  },
  {
    type: "function",
    name: "canWithdraw",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "shares" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "sharePrice",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "genesisEthPerShare",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "setGenesisEthPerShare",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "weiPerShare" }],
    outputs: [],
  },
  {
    type: "function",
    name: "position",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [
      { type: "uint256", name: "shares" },
      { type: "uint256", name: "value" },
      { type: "uint256", name: "cost" },
      { type: "uint256", name: "price" },
    ],
  },
  {
    type: "function",
    name: "costBasis",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "totalAssets",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "totalSupply",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "wethBuffer",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "issueFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint16" }],
  },
  {
    type: "function",
    name: "redeemFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint16" }],
  },
  {
    type: "function",
    name: "minDeposit",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "minFirstDeposit",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "minSleeveWeth",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "cashBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "paused",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "name",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "symbol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "creatorFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint16" }],
  },
  {
    type: "function",
    name: "protocolFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint16" }],
  },
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "nTokens",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "tokenAt",
    stateMutability: "view",
    inputs: [{ type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "addToken",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address", name: "token" },
      { type: "bytes32", name: "poolRef" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "addTokens",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address[]", name: "who" },
      { type: "bytes32[]", name: "pools" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "removeToken",
    stateMutability: "nonpayable",
    inputs: [{ type: "address", name: "token" }],
    outputs: [],
  },
  {
    type: "function",
    name: "removeTokens",
    stateMutability: "nonpayable",
    inputs: [{ type: "address[]", name: "who" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setCreatorRecipient",
    stateMutability: "nonpayable",
    inputs: [{ type: "address", name: "who" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setCreatorFee",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint16", name: "bps" }],
    outputs: [],
  },
  {
    type: "function",
    name: "transferOwnership",
    stateMutability: "nonpayable",
    inputs: [{ type: "address", name: "next" }],
    outputs: [],
  },
  {
    type: "function",
    name: "acceptOwnership",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelOwnershipTransfer",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "pendingOwner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "creatorRecipient",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "creator",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "constituents",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address[]" }],
  },
  {
    type: "function",
    name: "setTargets",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address[]", name: "who" },
      { type: "uint16[]", name: "bps" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "swapV3",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address", name: "tokenIn" },
      { type: "address", name: "tokenOut" },
      { type: "uint256", name: "amountIn" },
      { type: "uint256", name: "amountOutMin" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "restoreCash",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address", name: "token" },
      { type: "uint256", name: "amountIn" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "warmOracles",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "setFloors",
    stateMutability: "nonpayable",
    inputs: [
      { type: "uint256", name: "minDep" },
      { type: "uint256", name: "minFirst" },
      { type: "uint256", name: "minSleeve" },
      { type: "uint16", name: "cashBps_" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "priceWethWad",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "quoteOut",
    stateMutability: "view",
    inputs: [
      { type: "address", name: "tokenIn" },
      { type: "address", name: "tokenOut" },
      { type: "uint256", name: "amountIn" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "minOutFloor",
    stateMutability: "view",
    inputs: [{ type: "uint256", name: "twapOut" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "cashShortfall",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "oracleReady",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "poolOf",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "poolIdOf",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "bytes32" }],
  },
  {
    type: "function",
    name: "isV4",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "targetBps",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "uint16" }],
  },
  {
    type: "function",
    name: "lastPxWad",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "listed",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "cashTargetBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint16" }],
  },
] as const;

export const erc20Abi = [
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "uint256" }],
  },
] as const;

export const factoryAbi = [
  {
    type: "function",
    name: "create696x",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address[]", name: "tokens" },
      { type: "bytes32[]", name: "pools" },
      { type: "address", name: "recipient_" },
    ],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "create",
    stateMutability: "nonpayable",
    inputs: [
      { type: "string", name: "name_" },
      { type: "string", name: "symbol_" },
      { type: "string", name: "slug" },
      { type: "address[]", name: "tokens" },
      { type: "bytes32[]", name: "pools" },
      { type: "uint16", name: "creatorFeeBps" },
      { type: "address", name: "recipient_" },
    ],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "bySlug",
    stateMutability: "view",
    inputs: [{ type: "string" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "protocolFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint16" }],
  },
  {
    type: "function",
    name: "indexCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "implementation",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "treasury",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "indexAt",
    stateMutability: "view",
    inputs: [{ type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "slugOf",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "string" }],
  },
] as const;

export const quoterAbi = [
  {
    type: "function",
    name: "quoteExactInputSingle",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "params",
        type: "tuple",
        components: [
          { name: "tokenIn", type: "address" },
          { name: "tokenOut", type: "address" },
          { name: "amountIn", type: "uint256" },
          { name: "fee", type: "uint24" },
          { name: "sqrtPriceLimitX96", type: "uint160" },
        ],
      },
    ],
    outputs: [
      { name: "amountOut", type: "uint256" },
      { name: "sqrtPriceX96After", type: "uint160" },
      { name: "initializedTicksCrossed", type: "uint32" },
      { name: "gasEstimate", type: "uint256" },
    ],
  },
] as const;
