import fs from "node:fs"; import serverLib from "node:http";
import {createPublicClient,encodeFunctionData,formatEther,getAddress,http,keccak256,parseAbi,toHex} from "viem";
const rpc=process.env.ROBINHOOD_RPC_URL?.trim(); if(!rpc) throw Error("ROBINHOOD_RPC_URL is required");
const client=createPublicClient({transport:http(rpc,{timeout:20_000,retryCount:1})});
const live=JSON.parse(fs.readFileSync("deployments/huntx-v3-live.json","utf8"));
if(!["DEPLOYED_AWAITING_BASE_APPROVAL","APPROVED_AWAITING_BOOTSTRAP","LIVE_CLOSED_PILOT"].includes(live.status)||!/^0x[0-9a-f]{64}$/i.test(live.deploymentTx||"")||!/^0x[0-9a-f]{64}$/i.test(live.deployDataHash||"")) throw Error("Authenticated HUNTX deployment manifest required");
const account=getAddress("0x134D468B0bcaeA6DF127916f951F7938c06A37C6"), base=getAddress(live.baseIndex), vault=getAddress(live.vault);
const erc=parseAbi(["function approve(address,uint256) returns(bool)","function allowance(address,address) view returns(uint256)","function balanceOf(address) view returns(uint256)","function totalSupply() view returns(uint256)"]);
const va=parseAbi(["function bootstrap(address) payable","function bootstrapped() view returns(bool)","function weth() view returns(address)","function wethSeedAmount() view returns(uint256)","function initialShares() view returns(uint256)","function baseSeedAmounts() view returns(uint256[])"]);
const same=(a,b)=>a?.toLowerCase()===b?.toLowerCase();
async function state(){
 const [chain,done,weth,wethSeed,shares,amounts,allowance,baseBal,supply,huntBal,launcherCode,vaultCode,baseCode]=await Promise.all([client.getChainId(),client.readContract({address:vault,abi:va,functionName:"bootstrapped"}),client.readContract({address:vault,abi:va,functionName:"weth"}),client.readContract({address:vault,abi:va,functionName:"wethSeedAmount"}),client.readContract({address:vault,abi:va,functionName:"initialShares"}),client.readContract({address:vault,abi:va,functionName:"baseSeedAmounts"}),client.readContract({address:base,abi:erc,functionName:"allowance",args:[account,vault]}),client.readContract({address:base,abi:erc,functionName:"balanceOf",args:[account]}),client.readContract({address:vault,abi:erc,functionName:"totalSupply"}),client.readContract({address:vault,abi:erc,functionName:"balanceOf",args:[account]}),client.getCode({address:getAddress(live.launcher)}),client.getCode({address:vault}),client.getCode({address:base})]);
 if(keccak256(launcherCode)!==live.launcherRuntimeCodeHash||keccak256(vaultCode)!==live.vaultRuntimeCodeHash||keccak256(baseCode)!==live.baseRuntimeCodeHash) throw Error("Verified deployment bytecode changed");
 if(chain!==4663||amounts.length!==1||(!done&&baseBal<amounts[0])) throw Error("Verified HUNTX deployment or FEEX backing changed");
 return {done,weth,wethSeed,shares,baseAmount:amounts[0],allowance,supply,huntBal};
}
async function txFor(step){
 const s=await state(); if(s.done)return {done:true};
 let tx;
 if(step===1){if(s.allowance===s.baseAmount)return {already:true,next:2}; tx={account,to:base,data:encodeFunctionData({abi:erc,functionName:"approve",args:[vault,s.baseAmount]}),value:0n};}
 else {if(s.allowance!==s.baseAmount)throw Error("Complete the exact FEEX approval first"); tx={account,to:vault,data:encodeFunctionData({abi:va,functionName:"bootstrap",args:[account]}),value:s.wethSeed};}
 await client.call(tx); const gas=(await client.estimateGas(tx))*125n/100n,maxFee=(await client.getGasPrice())*2n,gasCap=gas*maxFee;
 if(await client.getBalance({address:account})<tx.value+gasCap)throw Error(`Curator needs ${formatEther(tx.value+gasCap)} ETH including gas`);
 return {done:false,step,base:formatEther(s.baseAmount),weth:formatEther(s.wethSeed),gas:formatEther(gasCap),tx:{from:account,to:tx.to,data:tx.data,value:toHex(tx.value),chainId:"0x1237",gas:toHex(gas),maxFeePerGas:toHex(maxFee),maxPriorityFeePerGas:"0x0"}};
}
async function receipt(step,hash){let r;try{r=await client.getTransactionReceipt({hash})}catch{return {confirmed:false}} if(r.status!=="success")throw Error(`Step ${step} reverted`); const tx=await client.getTransaction({hash});if(!same(tx.from,account))throw Error("Signer mismatch");const s=await state();
 if(step===1){if(!same(tx.to,base)||s.allowance!==s.baseAmount)throw Error("Approval receipt mismatch");live.status="APPROVED_AWAITING_BOOTSTRAP";}
 else {const wethBal=await client.readContract({address:s.weth,abi:erc,functionName:"balanceOf",args:[vault]});const baseVault=await client.readContract({address:base,abi:erc,functionName:"balanceOf",args:[vault]});if(!same(tx.to,vault)||!s.done||s.supply!==s.shares||s.huntBal!==s.shares||baseVault!==s.baseAmount||wethBal!==s.wethSeed||s.allowance!==0n)throw Error("Final backing verification failed");live.status="LIVE_CLOSED_PILOT";}
 live.lastVerified={step,hash,blockNumber:r.blockNumber.toString(),verifiedAt:new Date().toISOString()};fs.writeFileSync("deployments/huntx-v3-live.json",JSON.stringify(live,null,2)+"\n");return {confirmed:true,status:live.status,feeEth:formatEther(r.gasUsed*r.effectiveGasPrice)};}
const page=`<!doctype html><meta charset=utf-8><title>HOODX · Fund HUNTX</title><style>body{background:#07110f;color:#e9f7f4;font:18px system-ui;max-width:760px;margin:48px auto;padding:24px}main{border:1px solid #24443e;border-radius:24px;padding:30px;background:#10211e}h1{font-size:42px;margin:6px 0}button{width:100%;padding:18px;border:0;border-radius:14px;background:#53d8ca;font:700 19px system-ui;margin-top:14px}button:disabled{opacity:.38}pre{color:#a9c2bd;white-space:pre-wrap}</style><main><small>ROBINHOOD CHAIN · CLOSED PILOT</small><h1>Back HUNTX.</h1><p>Two explicit curator signatures: approve exactly 160 FEEX, then atomically transfer FEEX + 40% risk-reference WETH and mint 200 HUNTX. No launch token is purchased.</p><button id=c>Connect Rabby</button><button id=a disabled>1 · Approve exact FEEX</button><button id=b disabled>2 · Fund + mint HUNTX</button><pre id=s>Connect the official curator wallet.</pre></main><script src=/wallet.js></script>`;
const js=`let p,step=1;const s=document.querySelector('#s'),a=document.querySelector('#a'),b=document.querySelector('#b'),ps=[];addEventListener('eip6963:announceProvider',e=>{if(!ps.some(x=>x.info.uuid===e.detail.info.uuid))ps.push(e.detail)});dispatchEvent(new Event('eip6963:requestProvider'));const pick=()=>ps.find(x=>/rabby/i.test(x.info.name))?.provider||ethereum?.providers?.find(x=>x.isRabby)||(ethereum?.isRabby?ethereum:null);async function prep(n){const x=await(await fetch('/prepare?step='+n)).json();if(x.error)throw Error(x.error);if(x.done){s.textContent='HUNTX is already fully backed and live.';return}if(x.already){a.disabled=true;b.disabled=false;s.textContent='Exact FEEX approval verified. Step 2 is ready.';return}s.textContent='Step '+n+' simulation passed. FEEX '+x.base+', WETH '+x.weth+', max gas '+x.gas+'.';(n===1?a:b).disabled=false}c.onclick=async()=>{try{dispatchEvent(new Event('eip6963:requestProvider'));await new Promise(r=>setTimeout(r,250));p=pick();if(!p)throw Error('Rabby not detected');const x=await p.request({method:'eth_requestAccounts'});if(x[0]?.toLowerCase()!=='${account.toLowerCase()}')throw Error('Select the official curator wallet');if(BigInt(await p.request({method:'eth_chainId'}))!==4663n)await p.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x1237'}]});await prep(1)}catch(e){s.textContent=e.message}};async function send(n){try{a.disabled=b.disabled=true;const x=await(await fetch('/prepare?step='+n)).json();if(x.error)throw Error(x.error);const h=await p.request({method:'eth_sendTransaction',params:[x.tx]});s.textContent='Submitted '+h+' — verifying…';for(let i=0;i<120;i++){const y=await(await fetch('/receipt?step='+n+'&hash='+h)).json();if(y.error)throw Error(y.error);if(y.confirmed){s.textContent=y.status+' · gas '+y.feeEth+' ETH';if(n===1)await prep(2);return}await new Promise(r=>setTimeout(r,3000))}throw Error('Still pending; inspect before retrying')}catch(e){s.textContent=e.message+' No automatic retry was sent.'}}a.onclick=()=>send(1);b.onclick=()=>send(2);`;
const server=serverLib.createServer(async(req,res)=>{res.setHeader("Cache-Control","no-store");res.setHeader("X-Frame-Options","DENY");res.setHeader("Content-Security-Policy","default-src 'self';style-src 'unsafe-inline';script-src 'self';connect-src 'self'");if(req.headers.host!=="127.0.0.1:8798"||req.method!=="GET"){res.writeHead(403);return res.end()}try{const u=new URL(req.url,"http://127.0.0.1:8798");if(u.pathname==="/")return res.end(page);if(u.pathname==="/wallet.js"){res.setHeader("Content-Type","text/javascript");return res.end(js)}res.setHeader("Content-Type","application/json");if(u.pathname==="/prepare")return res.end(JSON.stringify(await txFor(Number(u.searchParams.get("step")))));if(u.pathname==="/receipt"){const h=u.searchParams.get("hash");if(!/^0x[0-9a-f]{64}$/i.test(h||""))throw Error("Invalid hash");return res.end(JSON.stringify(await receipt(Number(u.searchParams.get("step")),h)))}res.writeHead(404);res.end("{}") }catch(e){res.writeHead(400);res.end(JSON.stringify({error:(e.message||"Request failed").replace(/https?:\/\/\S+/g,"<redacted>")}))}});
server.listen(8798,"127.0.0.1",()=>console.log("HUNTX V3 signer: http://127.0.0.1:8798"));
