/* Synthetic local-chain integration only. Never accepts a remote RPC or real wallet. */
const fs=require('node:fs'), path=require('node:path'), {spawn,spawnSync}=require('node:child_process');
const compiled=spawnSync(process.execPath,['node_modules/typescript/bin/tsc','--strict','--noEmitOnError','--skipLibCheck','--esModuleInterop','--module','commonjs','--target','es2022','--outDir','node_modules/.cache/hoodx-e2e','lib/proportionalQuote.ts','lib/proportionalSolver.ts','lib/proportionalPlan.ts','lib/proportionalRelease.ts'],{stdio:'inherit',windowsHide:true});
if(compiled.status!==0)process.exit(1);
const {createPublicClient,createWalletClient,http,parseEther,encodeAbiParameters,parseAbiParameters,zeroAddress}=require('viem');
const {readProportionalState,quoteProportionalDeposit,quoteProportionalWithdrawal,prepareProportionalDeposit,prepareProportionalWithdrawal}=require('../node_modules/.cache/hoodx-e2e/proportionalQuote.js');
const {verifyProportionalRelease}=require('../node_modules/.cache/hoodx-e2e/proportionalRelease.js');
const endpoint='http://127.0.0.1:18547';
const chain={id:4663,name:'HOODX synthetic test chain',nativeCurrency:{name:'ETH',symbol:'ETH',decimals:18},rpcUrls:{default:{http:[endpoint]}}};
const child=spawn(path.resolve('../work/foundry/anvil.exe'),['--host','127.0.0.1','--port','18547','--chain-id','4663','--silent'],{stdio:'ignore',windowsHide:true});
const client=createPublicClient({chain,transport:http(endpoint,{retryCount:0})});
const artifact=name=>JSON.parse(fs.readFileSync(path.join('out',`${name}.sol`,`${name}.json`),'utf8'));
const fixture=name=>JSON.parse(fs.readFileSync(path.join('out','VaultV2.t.sol',`${name}.json`),'utf8'));
const assert=(condition,message)=>{if(!condition)throw Error(message);};
(async()=>{
  let healthy=false;
  for(let i=0;i<40;i++){try{healthy=await client.getChainId()===4663;if(healthy)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  assert(healthy,'Local test node did not start');
  assert(child.exitCode===null,'Refusing to use a pre-existing node');
  assert((await client.request({method:'web3_clientVersion'})).toLowerCase().includes('anvil'),'Not a synthetic Anvil node');
  assert(await client.getBlockNumber()===0n,'Refusing a nonempty local chain');
  const accounts=await client.request({method:'eth_accounts'});
  const [owner,alice]=accounts;
  assert(owner.toLowerCase()==='0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266','Unexpected local fixture account');
  const wallet=createWalletClient({chain,transport:http(endpoint),account:owner});
  const wait=async hash=>{const receipt=await client.waitForTransactionReceipt({hash});assert(receipt.status==='success','Local transaction failed');return receipt;};
  const deploy=async(a,args=[])=>{const r=await wait(await wallet.deployContract({abi:a.abi,bytecode:a.bytecode.object,args}));return r.contractAddress;};
  const send=async(params)=>{const {request,result}=await client.simulateContract({account:owner,...params});await wait(await wallet.writeContract(request));return result;};
  const token=fixture('TestTokenV2'),weth=fixture('TestWethV2'),executor=fixture('TestExecutorV2');
  const w=await deploy(weth),a=await deploy(token,['A']),b=await deploy(token,['B']),ex=await deploy(executor,[w]);
  const policyArtifact=artifact('HoodxProportionalPolicyV3'),feeArtifact=artifact('HoodxFeeModelV3'),vaultArtifact=artifact('HoodxProportionalV3'),factoryArtifact=artifact('HoodxProportionalFactoryV3');
  const policy=await deploy(policyArtifact,[owner,ex]),fees=await deploy(feeArtifact,[ex,zeroAddress,zeroAddress]);
  const impl=await deploy(vaultArtifact,[policy,fees]),factory=await deploy(factoryArtifact,[owner,accounts[2],impl]);
  const routeType=parseAbiParameters('(uint8 kind,address tokenIn,address tokenOut,uint24 fee,(address currency0,address currency1,uint24 fee,int24 tickSpacing,address hooks) key,uint256 minHopPriceX36,bytes hookData)[]');
  const route=(t,buy)=>encodeAbiParameters(routeType,[[{kind:3,tokenIn:buy?w:t,tokenOut:buy?t:w,fee:3000,key:{currency0:zeroAddress,currency1:zeroAddress,fee:0,tickSpacing:0,hooks:zeroAddress},minHopPriceX36:0n,hookData:'0x'}]]);
  const ids=[];
  for(const t of [a,b])ids.push(await send({address:policy,abi:policyArtifact.abi,functionName:'approveRoute',args:[t,route(t,true),route(t,false),'0x'+'11'.repeat(32)]}));
  await send({address:factory,abi:factoryArtifact.abi,functionName:'create',args:['localtest',{curator:owner,creator:owner,recipient:accounts[3],treasury:accounts[2],name:'Local basket',symbol:'LOCAL',creatorFee:40,protocolFee:10,cashBps:2500,firstDeposit:parseEther('0.02'),image:''},ids,[3750,3750]]});
  const vault=await client.readContract({address:factory,abi:factoryArtifact.abi,functionName:'bySlug',args:['localtest']});
  await verifyProportionalRelease(client,{vault,implementation:impl,factory,slug:'localtest',launchBlock:1n});
  let block=await client.getBlock(),nonce=await client.readContract({address:vault,abi:vaultArtifact.abi,functionName:'planNonce'});
  await send({address:vault,abi:vaultArtifact.abi,functionName:'bootstrap',args:[[parseEther('0.037'),parseEther('0.037')],nonce,block.timestamp+180n],value:parseEther('0.1')});
  let state=await readProportionalState(client,vault,alice);
  const plan=await quoteProportionalDeposit(client,state,parseEther('0.05'),()=>state.timestamp+1);
  const join=await prepareProportionalDeposit(client,state,plan);
  await wait(await wallet.writeContract({...join.request,account:alice}));
  state=await readProportionalState(client,vault,alice);
  assert(state.walletShares===plan.shares,'Signed shares were not minted');
  const exit=await quoteProportionalWithdrawal(client,state,state.walletShares,()=>state.timestamp+1);
  const prepared=await prepareProportionalWithdrawal(client,state,exit);
  await wait(await wallet.writeContract({...prepared.request,account:alice}));
  assert((await readProportionalState(client,vault,alice)).walletShares===0n,'Max exit left shares');
  state=await readProportionalState(client,vault,owner);
  const finalQuote=await quoteProportionalWithdrawal(client,state,state.walletShares,()=>state.timestamp+1);
  const finalExit=await prepareProportionalWithdrawal(client,state,finalQuote);
  await wait(await wallet.writeContract(finalExit.request));
  const empty=await readProportionalState(client,vault,owner);
  assert(empty.supply===0n&&empty.cash===0n&&empty.balances.every(n=>n===0n),'Final recovery left free assets');
  console.log('PASS: real frontend adapter -> vault-native quotes -> simulated protected transactions -> local receipts -> zero final shares/free assets. Synthetic local chain only.');
})().catch(error=>{console.error(error.shortMessage||error.message);process.exitCode=1;}).finally(()=>child.kill());
